#!/bin/bash

# Created automatically by parse-lyme-minutes.py

curl -L -o "Select_Board_Minutes_2023-12-28.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-359"
curl -L -o "Select_Board_Minutes_2023-12-14.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-358"
curl -L -o "Select_Board_Minutes_2023-11-30.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-357"
curl -L -o "Select_Board_Minutes_2023-11-16.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-356"
curl -L -o "Select_Board_Minutes_2023-11-02.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-355"
curl -L -o "Select_Board_Minutes_2023-10-26.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-354"
curl -L -o "Select_Board_Minutes_2023-10-19.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-353"
curl -L -o "Select_Board_Minutes_2023-10-05.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-352"
curl -L -o "Select_Board_Minutes_2023-09-21.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-351"
curl -L -o "Select_Board_Minutes_2023-09-05.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-350"
curl -L -o "Select_Board_Minutes_2023-08-24.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-349"
curl -L -o "Select_Board_Minutes_2023-08-10.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-348"
curl -L -o "Select_Board_Minutes_2023-07-13.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-347"
curl -L -o "Select_Board_Minutes_2023-06-29.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-346"
curl -L -o "Select_Board_Minutes_2023-06-15.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-345"
curl -L -o "Select_Board_Minutes_2023-06-01.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-344"
curl -L -o "Select_Board_Minutes_2023-05-18.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-343"
curl -L -o "Select_Board_Minutes_2023-05-04.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-342"
curl -L -o "Select_Board_Minutes_2023-04-20.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-340"
curl -L -o "Select_Board_Minutes_2023-04-06.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-341"
curl -L -o "Select_Board_Minutes_2023-03-23.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-339"
curl -L -o "Select_Board_Minutes_2023-03-09.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-338"
curl -L -o "Select_Board_Minutes_2023-02-23.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-337"
curl -L -o "Select_Board_Minutes_2023-02-09.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-336"
curl -L -o "Select_Board_Minutes_2023-02-08.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-335"
curl -L -o "Select_Board_Attachment_to_Minutes_2023-02-08.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-attachment-minutes-3"
curl -L -o "Select_Board_Minutes_2023-01-26.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-334"
curl -L -o "Select_Board_Attachment_to_Minutes_2023-01-26.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-attachment-minutes-2"
curl -L -o "Select_Board_Minutes_2023-01-23.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-333"
curl -L -o "Select_Board_Minutes_2023-01-12.pdf" "https://www.lymenh.gov/select-board/minutes/select-board-minutes-332"
